# Project information
site_name: Khartis Documentation
site_description: Documentation de Khartis, outil de cartographie thématique
site_author: Sciences Po - Atelier de cartographie
site_url: 'http://www.sciencespo.fr/cartographie/khartis/docs'

extra_javascript: [extra.js]

# Google Analytics
google_analytics:
  - 'UA-78393617-2'
  - 'Khartis'

# Copyright
copyright: Creative Commons CC BY NC ND

# Repository
repo_name: 'AtelierCartographie/Khartis'
repo_url: 'https://github.com/AtelierCartographie/Khartis'

# Theme and options
theme:
  name: 'material'
  language: 'fr'
  logo: './assets/Khartis-logo.svg'
  favicon: './assets/favicon.ico'
  palette:
    primary: ''
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false
extra_css:
  - 'stylesheets/extra.css'

# Navigation
nav:
    - Accueil: index.md
    - Tutoriels:
        - Premiers pas avec Khartis (1): premiers-pas-avec-Khartis-(1).md
        - Premiers pas avec Khartis (2): premiers-pas-avec-Khartis-(2).md
        - Importer son propre fond de carte: importer-propre-fond.md
        - Gestion des étiquettes: gestion-etiquettes.md
    - Visualisations:
        - Liste des visualisations: liste-des-visualisations.md
        - Symboles proportionnels: symboles-proportionnels.md
        - Couleurs ordonnées: couleurs-ordonnees.md
        - Symboles ordonnées: symboles-ordonnes.md
        - Symboles différents: symboles-differents.md
        - Couleurs différentes: couleurs-differentes.md
        - Symboles proportionnels colorés (ordre): symboles-proportionnels-colores-ordre.md
        - Symboles proportionnels colorés (différence): symboles-proportionnels-colores-difference.md
        - Double symboles proportionnels: double-symboles-proportionnels.md
    - Ressources:
        - Importer des données: importer-des-donnees.md
        - Les fonds de carte disponibles: les-fonds-de-carte-disponibles.md
        - Les projections disponibles: les-projections-disponibles.md
        - Les sources des exemples à disposition: les-sources-des-exemples-a-disposition.md
        - Discrétisation: discretisation.md
        - Le contraste: contraste.md
        - FAQ: FAQ.md
    - Définitions: definitions.md
    - Historique des versions: changelog.md
    - Contribute:
        - Add a basemap: how-to-create-a-basemap-for-Khartis.md
