image: docker:stable

stages:
  - build
  - deploy

build:
  stage: build
  image: node:8.16.2-alpine
  script:
    - apk add --update git python2 py-setuptools
    - easy_install-2.7 pip
    - pip install mkdocs==1.0.4 mkdocs-material==4.5.0
    - yarn install
    - cp config/environment.js.tpl config/environment.js
    - ./node_modules/.bin/ember khartis:build --environment=production --thumbnails=false
  environment:
    name: $CI_COMMIT_REF_SLUG
  artifacts:
    paths:
    - dist
    expire_in: 1 week
  only:
    - master
    - production

deploy:
  stage: deploy
  image: instrumentisto/rsync-ssh
  dependencies: 
    - build
  environment:
    name: $CI_COMMIT_REF_SLUG
  variables:
    GIT_STRATEGY: none
  script:
    - chmod o-rwx $RSYNC_PASSWORD_FILE
    - rsync  -avz --password-file=$RSYNC_PASSWORD_FILE  dist/  $RSYNC_USER@$RSYNC_HOST::$RSYNC_MODULE/
  only:
    - master
    - production
